@RKAnchor.Server_HostAddress = https://localhost:7048

GET {{RKAnchor.Server_HostAddress}}/weatherforecast/
Accept: application/json


###
GET {{RKAnchor.Server_HostAddress}}/product
Accept: application/json

